Update python in CI/CD
https://github.com/SUSE/qe-sap-deployment/actions/runs/3803551452/jobs/6470034547

```
Error: The version '3.6' with architecture 'x64' was not found for Ubuntu 22.04.
```

Update to 3.6.15