Update python in CI/CD (#114)
The CI/CD of this project is using ubuntu-latest that has been recently promoted to 22.04
https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/

But python 3.6 is not supported on this platform:
https://github.com/SUSE/qe-sap-deployment/actions/runs/3803551452/jobs/6470034547

Error: The version '3.6' with architecture 'x64' was not found for Ubuntu 22.04.

Fix Ubuntu to 20.4 and update python 3.6 to 3.6.15. Also update 3.8 to 3.9.15 to reflect what is used in openQA after os-autoinst/os-autoinst-distri-opensuse#15895